coverage:
  status:
    project: off
      # default:
        # basic
        # target: auto #default
        # base: auto
    patch:
      default:
        target: 40%
        informational: false
        if_ci_failed: error
        
# https://docs.codecov.com/docs/pull-request-comments#disable-comment
comment: false
