line-length: false
no-inline-html: false
first-line-heading: false
no-alt-text: false
ol-prefix: false
no-duplicate-heading: false
single-h1: false
no-emphasis-as-heading: false
no-hard-tabs:
  code_blocks: true
  spaces_per_tab: 2