name: Kmesh CI Workflow

on: pull_request

jobs:

  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go-version: [ '1.22' ]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4.0.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run gen-check
      run: |
        make gen-check

    - name: Build Kmesh
      shell: bash
      run: |
        sudo env "PATH=$PATH" bash ./build.sh

    - name: Go Test
      run: |
        sudo env LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:$GITHUB_WORKSPACE/api/v2-c:$GITHUB_WORKSPACE/bpf/deserialization_to_bpf_map PKG_CONFIG_PATH=$GITHUB_WORKSPACE/mk | 
        go test -v -vet=off ./pkg/...
